parameters:
#    abshore_mail.example.class: Abshore\MailBundle\Example

services:
#    abshore_mail.example:
#        class: %abshore_mail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
